/* ==================================== JUCER_BINARY_RESOURCE ====================================

   This is an auto-generated file: Any edits you make may be overwritten!

*/

#include <cstring>

namespace BinaryData
{

//================== app.js ==================
static const unsigned char temp_binary_data_0[] =
"// Auric Z-CLIP WebUI \xe2\x80\x94 app.js\n"
"// FIX: os2x toggle ONLY on purple LED (.led). 2X is NOT a toggle.\n"
"\n"
"(() => {\n"
"  const PARAMS = new Set([\"pre\",\"trim\",\"satclip\",\"mix\",\"drive\",\"ceiling\",\"os2x\"]);\n"
"  const DEFAULTS = { pre:0.35, trim:0.35, satclip:0.5, mix:1.0, drive:0.5, ceiling:0.7, os2x:0 };\n"
"\n"
"  const clamp01 = (v) => Math.min(1, Math.max(0, v));\n"
"  const valueToDeg = (v) => -135 + v * 270;\n"
"  const quantizeOs2x = (v) => (v >= 0.5 ? 1 : 0);\n"
"\n"
"  // Queue host calls if __setParam comes before DOM ready\n"
"  const __hostQueue = [];\n"
"  const __earlySetParam = (id, value) => { __hostQueue.push([id, value]); };\n"
"  if (typeof window.__setParam !== \"function\") window.__setParam = __earlySetParam;\n"
"\n"
"  const postParam = (id, value) => {\n"
"    try {\n"
"      if (window.juce && typeof window.juce.postMessage === \"function\") {\n"
"        window.juce.postMessage(JSON.stringify({ type: \"param\", id, value }));\n"
"      }\n"
"    } catch {}\n"
"  };\n"
"\n"
"  const boot = () => {\n"
"    // Initial UI state (host overrides via __setParam)\n"
"    const state = { pre:0.5, trim:0.5, satclip:0.5, mix:0.5, drive:0.5, ceiling:0.5, os2x:0 };\n"
"\n"
"    const knobEls = {};\n"
"    document.querySelectorAll(\".small-knob, .drive-knob\").forEach((el) => {\n"
"      const id = el.dataset.param;\n"
"      if (id) knobEls[id] = el;\n"
"    });\n"
"\n"
"    const sliderTrack = document.querySelector(\".slider-track\");\n"
"    const sliderThumb = document.querySelector(\".slider-thumb\");\n"
"    const led = document.querySelector('.led[data-param=\"os2x\"]');\n"
"\n"
"    const applyPowerClass = (on) => {\n"
"      const root = document.documentElement;\n"
"      root.classList.toggle(\"powerOn\", !!on);\n"
"      root.classList.toggle(\"powerOff\", !on);\n"
"    };\n"
"\n"
"    const applyKnob = (id, value) => {\n"
"      const el = knobEls[id];\n"
"      if (!el) return;\n"
"      el.style.setProperty(\"--rot\", `${valueToDeg(value)}deg`);\n"
"    };\n"
"\n"
"    const applySlider = (value) => {\n"
"      if (!sliderTrack || !sliderThumb) return;\n"
"\n"
"      const w = sliderTrack.clientWidth || sliderTrack.getBoundingClientRect().width;\n"
"      const tw = sliderThumb.offsetWidth || sliderThumb.getBoundingClientRect().width;\n"
"      if (!w || !tw) return;\n"
"\n"
"      const min = tw / 2;\n"
"      const max = w - tw / 2;\n"
"      const x = min + clamp01(value) * (max - min);\n"
"      sliderThumb.style.left = `${x}px`;\n"
"    };\n"
"\n"
"    const applyLed = (value) => {\n"
"      const on = value >= 0.5;\n"
"      if (led) led.classList.toggle(\"isOn\", on);\n"
"      applyPowerClass(on);\n"
"    };\n"
"\n"
"    const applyParam = (id, value) => {\n"
"      if (!PARAMS.has(id)) return;\n"
"      const v = id === \"os2x\" ? quantizeOs2x(value) : clamp01(value);\n"
"      state[id] = v;\n"
"\n"
"      if (id === \"ceiling\") { applySlider(v); return; }\n"
"      if (id === \"os2x\")    { applyLed(v);    return; }\n"
"      applyKnob(id, v);\n"
"    };\n"
"\n"
"    const setParam = (id, value, fromHost = false) => {\n"
"      if (!PARAMS.has(id)) return;\n"
"      const v = id === \"os2x\" ? quantizeOs2x(value) : clamp01(value);\n"
"\n"
"      applyParam(id, v);\n"
"      if (!fromHost) postParam(id, v);\n"
"    };\n"
"\n"
"    const setSliderFromClientX = (clientX) => {\n"
"      if (!sliderTrack) return;\n"
"      const rect = sliderTrack.getBoundingClientRect();\n"
"      if (!rect.width) return;\n"
"      const raw = (clientX - rect.left) / rect.width;\n"
"      setParam(\"ceiling\", clamp01(raw), false);\n"
"    };\n"
"\n"
"    // ===== KNOBS =====\n"
"    document.querySelectorAll(\".small-knob, .drive-knob\").forEach((el) => {\n"
"      el.addEventListener(\"pointerdown\", (e) => {\n"
"        if (e.pointerType === \"mouse\" && e.button !== 0) return;\n"
"        const id = el.dataset.param;\n"
"        if (!id) return;\n"
"\n"
"        e.preventDefault();\n"
"        e.stopPropagation();\n"
"\n"
"        const startY = e.clientY;\n"
"        const startValue = state[id] ?\? 0.5;\n"
"        const pid = e.pointerId;\n"
"\n"
"        try { el.setPointerCapture(pid); } catch {}\n"
"\n"
"        const onMove = (ev) => {\n"
"          if (ev.pointerId !== pid) return;\n"
"          const dy = startY - ev.clientY;\n"
"          setParam(id, clamp01(startValue + dy / 200), false);\n"
"        };\n"
"\n"
"        const onUp = (ev) => {\n"
"          if (ev.pointerId !== pid) return;\n"
"          try { el.releasePointerCapture(pid); } catch {}\n"
"          el.removeEventListener(\"pointermove\", onMove);\n"
"          el.removeEventListener(\"pointerup\", onUp);\n"
"          el.removeEventListener(\"pointercancel\", onUp);\n"
"        };\n"
"\n"
"        el.addEventListener(\"pointermove\", onMove);\n"
"        el.addEventListener(\"pointerup\", onUp);\n"
"        el.addEventListener(\"pointercancel\", onUp);\n"
"      }, { passive:false });\n"
"\n"
"      el.addEventListener(\"dblclick\", () => {\n"
"        const id = el.dataset.param;\n"
"        if (!id || DEFAULTS[id] === undefined) return;\n"
"        setParam(id, DEFAULTS[id], false);\n"
"      });\n"
"\n"
"      el.addEventListener(\"wheel\", (e) => {\n"
"        const id = el.dataset.param;\n"
"        if (!id) return;\n"
"        e.preventDefault();\n"
"\n"
"        const dir = e.deltaY < 0 ? 1 : -1;\n"
"        let step = 0.01;\n"
"        if (e.shiftKey) step = 0.05;\n"
"        if (e.altKey) step = 0.002;\n"
"\n"
"        setParam(id, clamp01((state[id] ?\? 0.5) + dir * step), false);\n"
"      }, { passive:false });\n"
"    });\n"
"\n"
"    // ===== SLIDER =====\n"
"    if (sliderTrack && sliderThumb) {\n"
"      const startSlider = (e) => {\n"
"        if (e.pointerType === \"mouse\" && e.button !== 0) return;\n"
"\n"
"        e.preventDefault();\n"
"        e.stopPropagation();\n"
"\n"
"        const pid = e.pointerId;\n"
"        const target = e.currentTarget;\n"
"\n"
"        try { target.setPointerCapture(pid); } catch {}\n"
"        setSliderFromClientX(e.clientX);\n"
"\n"
"        const onMove = (ev) => {\n"
"          if (ev.pointerId !== pid) return;\n"
"          setSliderFromClientX(ev.clientX);\n"
"        };\n"
"\n"
"        const onUp = (ev) => {\n"
"          if (ev.pointerId !== pid) return;\n"
"          try { target.releasePointerCapture(pid); } catch {}\n"
"          target.removeEventListener(\"pointermove\", onMove);\n"
"          target.removeEventListener(\"pointerup\", onUp);\n"
"          target.removeEventListener(\"pointercancel\", onUp);\n"
"        };\n"
"\n"
"        target.addEventListener(\"pointermove\", onMove);\n"
"        target.addEventListener(\"pointerup\", onUp);\n"
"        target.addEventListener(\"pointercancel\", onUp);\n"
"      };\n"
"\n"
"      sliderTrack.addEventListener(\"pointerdown\", startSlider, { passive:false });\n"
"      sliderThumb.addEventListener(\"pointerdown\", startSlider, { passive:false });\n"
"    }\n"
"\n"
"    // ===== LED ONLY (os2x) =====\n"
"    const toggleOs2x = () => {\n"
"      const next = quantizeOs2x((state.os2x ?\? 0) >= 0.5 ? 0 : 1);\n"
"      state.os2x = next;\n"
"      applyLed(next); // instant feedback\n"
"      postParam(\"os2x\", next);\n"
"    };\n"
"\n"
"    if (led) {\n"
"      led.addEventListener(\"pointerdown\", (e) => {\n"
"        if (e.pointerType === \"mouse\" && e.button !== 0) return;\n"
"\n"
"        e.preventDefault();\n"
"        e.stopPropagation();\n"
"\n"
"        led.classList.add(\"isPressed\");\n"
"        toggleOs2x();\n"
"      }, { passive:false });\n"
"\n"
"      led.addEventListener(\"pointerup\", () => { led.classList.remove(\"isPressed\"); }, { passive:true });\n"
"      led.addEventListener(\"pointercancel\", () => { led.classList.remove(\"isPressed\"); }, { passive:true });\n"
"      led.addEventListener(\"lostpointercapture\", () => { led.classList.remove(\"isPressed\"); }, { passive:true });\n"
"    }\n"
"\n"
"    // ===== Host -> UI =====\n"
"    window.__setParam = (id, value) => {\n"
"      if (!PARAMS.has(id)) return;\n"
"      const num = Number(value);\n"
"      if (Number.isNaN(num)) return;\n"
"\n"
"      setParam(id, num, true);\n"
"    };\n"
"\n"
"    // Flush queued host updates\n"
"    while (__hostQueue.length) {\n"
"      const [id, v] = __hostQueue.shift();\n"
"      try { window.__setParam(id, v); } catch {}\n"
"    }\n"
"\n"
"    const refreshUI = () => {\n"
"      Object.keys(state).forEach((id) => applyParam(id, state[id]));\n"
"    };\n"
"\n"
"    window.addEventListener(\"resize\", refreshUI);\n"
"    requestAnimationFrame(() => {\n"
"      refreshUI();\n"
"      requestAnimationFrame(refreshUI);\n"
"    });\n"
"\n"
"    applyPowerClass((state.os2x ?\? 0) >= 0.5);\n"
"  };\n"
"\n"
"  if (document.readyState === \"loading\") {\n"
"    window.addEventListener(\"DOMContentLoaded\", boot, { once:true });\n"
"  } else {\n"
"    boot();\n"
"  }\n"
"})();\n"
"\n"
"\n"
"// =======================\n"
"// Credits Modal\n"
"// =======================\n"
"(() => {\n"
"  const btn = document.getElementById(\"creditBtn\");\n"
"  const modal = document.getElementById(\"creditModal\");\n"
"  const closeBtn = document.getElementById(\"creditClose\");\n"
"\n"
"  if (!btn || !modal || !closeBtn) return;\n"
"\n"
"  const open = () => {\n"
"    modal.classList.add(\"isOpen\");\n"
"    modal.setAttribute(\"aria-hidden\", \"false\");\n"
"    closeBtn.focus?.();\n"
"  };\n"
"\n"
"  const close = () => {\n"
"    modal.classList.remove(\"isOpen\");\n"
"    modal.setAttribute(\"aria-hidden\", \"true\");\n"
"    btn.focus?.();\n"
"  };\n"
"\n"
"  btn.addEventListener(\"click\", open);\n"
"  closeBtn.addEventListener(\"click\", close);\n"
"\n"
"  // click outside modal to close\n"
"  modal.addEventListener(\"click\", (e) => {\n"
"    if (e.target === modal) close();\n"
"  });\n"
"\n"
"  // Esc to close\n"
"  window.addEventListener(\"keydown\", (e) => {\n"
"    if (e.key === \"Escape\" && modal.classList.contains(\"isOpen\")) close();\n"
"  });\n"
"})();\n";

const char* app_js = (const char*) temp_binary_data_0;

//================== index.html ==================
static const unsigned char temp_binary_data_1[] =
"<!DOCTYPE html>\n"
"<html lang=\"en\">\n"
"<head>\n"
"  <meta charset=\"UTF-8\" />\n"
"  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n"
"  <title>AURIC Z-CLIP</title>\n"
"  <link rel=\"stylesheet\" href=\"style.css\" />\n"
"</head>\n"
"\n"
"<body>\n"
"  <div class=\"panel\">\n"
"    <div class=\"grain\"></div>\n"
"\n"
"    <!-- Screws -->\n"
"    <div class=\"screw top-left\"></div>\n"
"    <div class=\"screw top-right\"></div>\n"
"    <div class=\"screw bottom-left\"></div>\n"
"    <div class=\"screw bottom-right\"></div>\n"
"\n"
"    <!-- Header -->\n"
"    <div id=\"auric\" class=\"header\">AURIC</div>\n"
"    <div id=\"zclip\" class=\"header\">Z-CLIP</div>\n"
"\n"
"    <!-- Knobs -->\n"
"    <div id=\"pre-group\" class=\"knob-group\">\n"
"      <div class=\"knob-label\">PRE</div>\n"
"      <div class=\"knob-stack\">\n"
"        <div class=\"tick-ring\"></div>\n"
"        <div class=\"small-knob\" data-param=\"pre\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div id=\"trim-group\" class=\"knob-group\">\n"
"      <div class=\"knob-label\">TRIM</div>\n"
"      <div class=\"knob-stack\">\n"
"        <div class=\"tick-ring\"></div>\n"
"        <div class=\"small-knob\" data-param=\"trim\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div id=\"satclip-group\" class=\"knob-group\">\n"
"      <div class=\"knob-label\">SAT/CLIP</div>\n"
"      <div class=\"knob-stack\">\n"
"        <div class=\"tick-ring\"></div>\n"
"        <div class=\"small-knob\" data-param=\"satclip\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <div id=\"mix-group\" class=\"knob-group\">\n"
"      <div class=\"knob-label\">MIX</div>\n"
"      <div class=\"knob-stack\">\n"
"        <div class=\"tick-ring\"></div>\n"
"        <div class=\"small-knob\" data-param=\"mix\"></div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"    <!-- Drive -->\n"
"    <div class=\"drive-container\">\n"
"      <div class=\"drive-outer\">\n"
"        <div class=\"drive-ring\"></div>\n"
"        <div class=\"drive-knob\" data-param=\"drive\"></div>\n"
"      </div>\n"
"      <div id=\"drive-label\">DRIVE</div>\n"
"    </div>\n"
"\n"
"    <!-- LED (POWER) -->\n"
"    <div class=\"led-container\">\n"
"      <div class=\"led\" data-param=\"os2x\" aria-label=\"Power / OS 2X\"></div>\n"
"    </div>\n"
"\n"
"    <!-- Output Ceiling -->\n"
"    <div class=\"output-container\">\n"
"      <div class=\"mini2x\" data-param=\"os2x\" aria-label=\"2X Toggle\"></div>\n"
"      <div class=\"mini2x-label\" data-param=\"os2x\">2X</div>\n"
"\n"
"      <div class=\"slider-track\" data-param=\"ceiling\">\n"
"        <div class=\"slider-thumb\" data-param=\"ceiling\"></div>\n"
"      </div>\n"
"\n"
"      <div class=\"tiny-hole\"></div>\n"
"      <div class=\"output-label\">OUTPUT CEILING</div>\n"
"    </div>\n"
"\n"
"    <!-- Bottom Line -->\n"
"    <div class=\"bottom-line\"></div>\n"
"        <!-- Credit / Info -->\n"
"    <button class=\"info-btn\" id=\"creditBtn\" type=\"button\" aria-label=\"Credits\">\n"
"      i\n"
"    </button>\n"
"        <!-- Credits Modal -->\n"
"    <div class=\"modal-backdrop\" id=\"creditModal\" aria-hidden=\"true\">\n"
"      <div class=\"modal\" role=\"dialog\" aria-modal=\"true\" aria-labelledby=\"creditTitle\">\n"
"        <div class=\"modal-head\">\n"
"          <div class=\"modal-title\" id=\"creditTitle\">CREDITS</div>\n"
"          <button class=\"modal-close\" id=\"creditClose\" type=\"button\" aria-label=\"Close\">\xc3\x97</button>\n"
"        </div>\n"
"\n"
"        <div class=\"modal-body\">\n"
"          <div class=\"credit-lines\">\n"
"            <div class=\"credit-row\">\n"
"              <span class=\"credit-k\">Plugin</span>\n"
"              <span class=\"credit-v\">AURIC Z-CLIP</span>\n"
"            </div>\n"
"            <div class=\"credit-row\">\n"
"              <span class=\"credit-k\">Version</span>\n"
"              <span class=\"credit-v\">v1.0</span>\n"
"            </div>\n"
"            <div class=\"credit-row\">\n"
"              <span class=\"credit-k\">UI</span>\n"
"              <span class=\"credit-v\">Matte Magenta / Brushed Metal</span>\n"
"            </div>\n"
"\n"
"            <div class=\"credit-divider\"></div>\n"
"\n"
"            <div class=\"credit-note\">\n"
"              Edit teks credit ini sesuai kebutuhan kamu.\n"
"            </div>\n"
"          </div>\n"
"        </div>\n"
"      </div>\n"
"    </div>\n"
"\n"
"\n"
"  </div>\n"
"\n"
"  <script src=\"app.js\"></script>\n"
"</body>\n"
"</html>\n";

const char* index_html = (const char*) temp_binary_data_1;

//================== style.css ==================
static const unsigned char temp_binary_data_2[] =
":root{\n"
"  /* ===== Theme (match REF: matte magenta + black brushed metal) ===== */\n"
"  --panel-bg:#06060a;\n"
"  --panel-hi:#13141a;\n"
"\n"
"  --accent:#b53a73;          /* matte magenta (less neon) */\n"
"  --accent-strong:#ff2ca3;   /* only for glow core */\n"
"  --accent-soft:#ff6ac8;\n"
"\n"
"  --text-engrave:rgba(225,225,225,.30);\n"
"  --text-engrave-weak:rgba(210,210,210,.20);\n"
"\n"
"  --glow-inner:rgba(196,62,126,.92);\n"
"  --glow-outer:rgba(196,62,126,.22);\n"
"\n"
"  /* ===== layout sizes ===== */\n"
"  --kSmall: clamp(56px, 8vw, 78px);\n"
"  --kRing: calc(var(--kSmall) + 28px);\n"
"  --kDrive: clamp(155px, 26vw, 215px);\n"
"}\n"
"\n"
"*{margin:0;padding:0;box-sizing:border-box;user-select:none;}\n"
"html,body{width:100%;height:100%;overflow:hidden;background:#000;}\n"
"\n"
"body{\n"
"  display:flex;\n"
"  align-items:center;\n"
"  justify-content:center;\n"
"  font-family:'Barlow','Segoe UI',Arial,sans-serif;\n"
"  background:\n"
"    radial-gradient(1200px 680px at 50% 105%, rgba(196,62,126,.14) 0%, rgba(196,62,126,0) 72%),\n"
"    radial-gradient(900px 520px at 50% 44%, rgba(255,255,255,.04) 0%, rgba(0,0,0,0) 62%),\n"
"    radial-gradient(1800px 1200px at 50% 50%, rgba(0,0,0,0) 0%, rgba(0,0,0,.86) 72%, rgba(0,0,0,.96) 100%),\n"
"    #040405;\n"
"}\n"
"\n"
"/* =======================\n"
"   PANEL (REF: horizontal brushed + strong frame)\n"
"   ======================= */\n"
".panel{\n"
"  aspect-ratio: 1280 / 853;\n"
"  width: min(96vw, calc(96vh * 1280 / 853));\n"
"  position: relative;\n"
"  overflow: hidden;\n"
"  border-radius: 10px;\n"
"\n"
"  /* base metal */\n"
"  background:\n"
"    linear-gradient(180deg, #15161a 0%, #0a0b0f 50%, #07070a 100%),\n"
"    var(--panel-bg);\n"
"\n"
"  border: 1px solid rgba(255,255,255,.035);\n"
"  box-shadow:\n"
"    0 36px 90px rgba(0,0,0,.86),\n"
"    0 16px 32px rgba(0,0,0,.62),\n"
"    inset 0 10px 22px rgba(0,0,0,.55),\n"
"    inset 0 -18px 34px rgba(0,0,0,.70),\n"
"    inset 0 0 0 1px rgba(255,255,255,.02);\n"
"}\n"
"\n"
"/* horizontal brushed + top highlight */\n"
".panel::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:0;\n"
"  pointer-events:none;\n"
"\n"
"  background:\n"
"    /* brushed lines (HORIZONTAL) */\n"
"    repeating-linear-gradient(\n"
"      90deg,\n"
"      rgba(255,255,255,.022) 0px,\n"
"      rgba(255,255,255,.008) 1px,\n"
"      rgba(0,0,0,.020) 3px,\n"
"      rgba(0,0,0,0) 6px\n"
"    ),\n"
"    /* top lip highlight */\n"
"    radial-gradient(120% 90% at 50% 0%, rgba(255,255,255,.10) 0%, rgba(255,255,255,0) 55%),\n"
"    /* gentle center falloff */\n"
"    radial-gradient(140% 120% at 50% 55%, rgba(255,255,255,.020) 0%, rgba(0,0,0,0) 56%);\n"
"\n"
"  mix-blend-mode: overlay;\n"
"  opacity:.85;\n"
"}\n"
"\n"
"/* inner frame + vignette (REF: strong edges) */\n"
".panel::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:10px;\n"
"  border-radius:9px;\n"
"  pointer-events:none;\n"
"\n"
"  background:\n"
"    /* edge vignette */\n"
"    radial-gradient(130% 120% at 50% 50%,\n"
"      rgba(0,0,0,0) 52%,\n"
"      rgba(0,0,0,.62) 82%,\n"
"      rgba(0,0,0,.86) 100%),\n"
"    /* subtle vertical shading */\n"
"    linear-gradient(180deg, rgba(255,255,255,.05), rgba(0,0,0,.18));\n"
"\n"
"  box-shadow:\n"
"    inset 0 0 0 1px rgba(255,255,255,.05),\n"
"    inset 0 0 0 2px rgba(0,0,0,.82),\n"
"    inset 0 24px 46px rgba(0,0,0,.42),\n"
"    inset 0 -22px 40px rgba(0,0,0,.54);\n"
"  opacity:.98;\n"
"}\n"
"\n"
"/* grain (keep subtle) */\n"
".grain{\n"
"  position:absolute;\n"
"  inset:0;\n"
"  pointer-events:none;\n"
"  opacity:.08;\n"
"  mix-blend-mode: overlay;\n"
"  background-image: url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='220' height='220'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='.75' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect w"
"idth='220' height='220' filter='url(%23n)' opacity='.55'/%3E%3C/svg%3E\");\n"
"  background-size:220px 220px;\n"
"}\n"
"\n"
"/* =======================\n"
"   Screws (more REF-like)\n"
"   ======================= */\n"
".screw{\n"
"  position:absolute;\n"
"  width:22px; height:22px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 38% 35%, #3a3a3e 0%, #17171a 62%, #040405 100%);\n"
"  border: 1px solid rgba(0,0,0,.90);\n"
"  box-shadow:\n"
"    0 8px 16px rgba(0,0,0,.86),\n"
"    inset 0 1px 2px rgba(255,255,255,.10),\n"
"    inset 0 -4px 6px rgba(0,0,0,.92);\n"
"  z-index:10;\n"
"}\n"
".screw::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:4px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    linear-gradient(90deg, transparent 44%, rgba(0,0,0,.72) 44% 56%, transparent 56%),\n"
"    linear-gradient(0deg, transparent 44%, rgba(0,0,0,.72) 44% 56%, transparent 56%),\n"
"    radial-gradient(circle at 40% 40%, rgba(255,255,255,.12), rgba(0,0,0,0) 60%);\n"
"  box-shadow:\n"
"    inset 0 1px 1px rgba(255,255,255,.08),\n"
"    inset 0 -2px 3px rgba(0,0,0,.82);\n"
"}\n"
".top-left{ top:14px; left:14px; }\n"
".top-right{ top:14px; right:14px; }\n"
".bottom-left{ bottom:14px; left:14px; }\n"
".bottom-right{ bottom:14px; right:14px; }\n"
"\n"
"/* =======================\n"
"   Headers (matte magenta - EXACT MATCH)\n"
"   ======================= */\n"
".header{\n"
"  position:absolute;\n"
"  top: 7%;\n"
"  font-size: clamp(30px, 5vw, 46px);\n"
"  font-weight:800;\n"
"  color: #b53a73; /* DIRECT HEX MATCH TO REFERENCE */\n"
"  letter-spacing: 1.1px;\n"
"  text-shadow:\n"
"    0 3px 10px rgba(0,0,0,.92),\n"
"    0 0 16px rgba(196,62,126,.14);\n"
"  z-index:5;\n"
"  text-transform: uppercase; /* ALL CAPS LIKE REFERENCE */\n"
"  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif; /* Explicit font declaration */\n"
"}\n"
"#auric{ left: 9.5%; }\n"
"#zclip{ right: 9.5%; }\n"
"\n"
"/* =======================\n"
"   Knob groups & labels (engraved - EXACT MATCH)\n"
"   ======================= */\n"
".knob-group{\n"
"  position:absolute;\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"  align-items:center;\n"
"  transform: translate(-50%, -50%);\n"
"  z-index:5;\n"
"}\n"
"\n"
".knob-label{\n"
"  color: var(--text-engrave);\n"
"  font-size: clamp(11px, 1.35vw, 15px);\n"
"  letter-spacing: 2.8px;\n"
"  margin-bottom: 12px;\n"
"  text-shadow:\n"
"    0 1px 0 rgba(0,0,0,.92),      /* engraved shadow */\n"
"    0 -1px 0 rgba(255,255,255,.08);\n"
"  opacity:.92;\n"
"  text-transform: uppercase; /* ALL CAPS LIKE REFERENCE */\n"
"  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif; /* Explicit font declaration */\n"
"}\n"
"\n"
".knob-stack{\n"
"  position:relative;\n"
"  width: var(--kRing);\n"
"  height: var(--kRing);\n"
"  display:flex;\n"
"  align-items:center;\n"
"  justify-content:center;\n"
"  filter: drop-shadow(0 16px 18px rgba(0,0,0,.68));\n"
"}\n"
"\n"
"/* =======================\n"
"   Tick ring (subtle hardware - LESS BUSY)\n"
"   ======================= */\n"
".tick-ring{\n"
"  position:absolute;\n"
"  inset:0;\n"
"  border-radius:50%;\n"
"  background:\n"
"    /* 12 subtle ticks (like reference image) */\n"
"    repeating-conic-gradient(\n"
"      from -140deg,\n"
"      rgba(255,255,255,.36) 0deg 1.5deg,\n"
"      rgba(255,255,255,0) 1.5deg 30deg\n"
"    ),\n"
"    /* rim shading */\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 62%, rgba(0,0,0,.62) 72%, rgba(0,0,0,0) 78%);\n"
"  -webkit-mask: radial-gradient(circle, transparent 0 58%, #000 63% 100%);\n"
"  mask: radial-gradient(circle, transparent 0 58%, #000 63% 100%);\n"
"  opacity:.72;\n"
"  box-shadow:\n"
"    0 2px 6px rgba(0,0,0,.44),\n"
"    inset 0 1px 0 rgba(255,255,255,.06),\n"
"    inset 0 -1px 0 rgba(0,0,0,.72);\n"
"}\n"
".tick-ring::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:0;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 32% 26%, rgba(255,255,255,.10), rgba(255,255,255,0) 52%),\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,.62) 66%, rgba(0,0,0,0) 76%);\n"
"  -webkit-mask: radial-gradient(circle, transparent 0 58%, #000 63% 100%);\n"
"  mask: radial-gradient(circle, transparent 0 58%, #000 63% 100%);\n"
"  opacity:.45;\n"
"}\n"
"\n"
"/* =======================\n"
"   Small knob (EXACT MATCH TO REFERENCE 2)\n"
"   ======================= */\n"
".small-knob{\n"
"  --rot:0deg;\n"
"  width: var(--kSmall);\n"
"  height: var(--kSmall);\n"
"  border-radius:50%;\n"
"  position:relative;\n"
"  cursor:pointer;\n"
"\n"
"  /* bevel stack */\n"
"  background:\n"
"    /* specular */\n"
"    radial-gradient(130% 105% at 30% 18%, rgba(255,255,255,.28) 0%, rgba(255,255,255,0) 34%),\n"
"    /* outer rim */\n"
"    radial-gradient(circle at 50% 50%, rgba(255,255,255,.06) 0 56%, rgba(0,0,0,0) 60%),\n"
"    /* deep bowl */\n"
"    radial-gradient(circle at 50% 58%, rgba(0,0,0,0) 0 34%, rgba(0,0,0,.55) 62%, rgba(0,0,0,.92) 100%),\n"
"    /* radial brushed */\n"
"    repeating-conic-gradient(from 0deg, rgba(255,255,255,.032) 0deg 0.9deg, rgba(0,0,0,0) 0.9deg 3deg),\n"
"    radial-gradient(circle at 50% 50%, #222226 0%, #121214 62%, #050506 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.94);\n"
"  box-shadow:\n"
"    0 14px 22px rgba(0,0,0,.72),\n"
"    0 2px 6px rgba(0,0,0,.76),\n"
"    inset 0 1px 2px rgba(255,255,255,.10),\n"
"    inset 0 18px 24px rgba(0,0,0,.54),\n"
"    inset 0 -18px 26px rgba(0,0,0,.86),\n"
"    inset 0 0 0 1px rgba(0,0,0,.78),\n"
"    inset 0 0 0 8px rgba(0,0,0,.20),\n"
"    inset 0 0 0 11px rgba(255,255,255,.03);\n"
"\n"
"  outline: 1px solid rgba(255,255,255,.04);\n"
"  outline-offset: -2px;\n"
"\n"
"  transform: rotate(var(--rot));\n"
"  transition: transform 80ms linear; /* smooth feel */\n"
"  touch-action: none;\n"
"}\n"
"\n"
"/* indicator (thick, like reference image) */\n"
".small-knob::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  left:50%;\n"
"  top:8px;\n"
"  width:2px;\n"
"  height:14px;\n"
"  transform: translateX(-50%);\n"
"  border-radius:2px;\n"
"  background: linear-gradient(180deg, rgba(255,255,255,.66), rgba(255,255,255,.10));\n"
"  box-shadow:\n"
"    0 1px 2px rgba(0,0,0,.74),\n"
"    inset 0 -1px 1px rgba(0,0,0,.45);\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"/* subtle knurl ring (LESS BUSY) */\n"
".small-knob::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-18%;\n"
"  border-radius:50%;\n"
"  background:\n"
"    repeating-conic-gradient(\n"
"      from -100deg,\n"
"      rgba(255,255,255,.12) 0deg 0.9deg,\n"
"      rgba(255,255,255,0) 0.9deg 12deg\n"
"    );\n"
"  -webkit-mask: radial-gradient(circle, transparent 0 60%, #000 64% 72%, transparent 74% 100%);\n"
"  mask: radial-gradient(circle, transparent 0 60%, #000 64% 72%, transparent 74% 100%);\n"
"  opacity:.22;\n"
"  pointer-events:none;\n"
"  transform: rotate(calc(-1 * var(--rot)));\n"
"}\n"
"\n"
"/* layout positions */\n"
"#pre-group     { left: 17.2%; top: 32.5%; }\n"
"#trim-group    { left: 17.2%; top: 60.8%; }\n"
"#satclip-group { left: 82.8%; top: 32.5%; }\n"
"#mix-group     { left: 82.8%; top: 60.8%; }\n"
"\n"
"/* =======================\n"
"   DRIVE\n"
"   ======================= */\n"
".drive-container{\n"
"  position:absolute;\n"
"  top: 41%;\n"
"  left: 50%;\n"
"  transform: translate(-50%, -50%);\n"
"  z-index:5;\n"
"  filter: drop-shadow(0 26px 32px rgba(0,0,0,.78)) drop-shadow(0 10px 14px rgba(0,0,0,.50));\n"
"}\n"
"\n"
"/* subtle magenta spill behind drive */\n"
".drive-container::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  left:50%; top:50%;\n"
"  transform: translate(-50%,-50%);\n"
"  width: calc(var(--kDrive) * 1.70);\n"
"  height: calc(var(--kDrive) * 1.40);\n"
"  border-radius: 999px;\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(196,62,126,.16) 0%, rgba(196,62,126,.08) 34%, rgba(196,62,126,0) 70%);\n"
"  opacity:.75;\n"
"  pointer-events:none;\n"
"  z-index:-1;\n"
"\n"
"  transition: opacity 520ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* outer housing */\n"
".drive-outer{\n"
"  width: var(--kDrive);\n"
"  height: var(--kDrive);\n"
"  border-radius:50%;\n"
"  position:relative;\n"
"\n"
"  background:\n"
"    /* top specular */\n"
"    radial-gradient(120% 90% at 34% 18%, rgba(255,255,255,.12) 0%, rgba(255,255,255,0) 42%),\n"
"    /* deep outer bowl */\n"
"    radial-gradient(circle at 50% 58%, rgba(0,0,0,0) 0 46%, rgba(0,0,0,.62) 70%, rgba(0,0,0,.96) 100%),\n"
"    /* brushed */\n"
"    repeating-conic-gradient(from 0deg, rgba(255,255,255,.020) 0deg 1.0deg, rgba(0,0,0,0) 1.0deg 3.8deg),\n"
"    radial-gradient(circle at 50% 50%, #232326 0%, #131315 62%, #050506 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.92);\n"
"  box-shadow:\n"
"    0 26px 38px rgba(0,0,0,.88),\n"
"    0 9px 14px rgba(0,0,0,.56),\n"
"    inset 0 2px 2px rgba(255,255,255,.06),\n"
"    inset 0 -28px 44px rgba(0,0,0,.90),\n"
"    inset 0 0 0 1px rgba(255,255,255,.03);\n"
"}\n"
"\n"
"/* thick bevel rim */\n"
".drive-outer::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-14px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 48%, rgba(0,0,0,.88) 62%, rgba(0,0,0,1) 76%),\n"
"    conic-gradient(from 315deg,\n"
"      rgba(255,255,255,.12) 0deg 40deg,\n"
"      rgba(255,255,255,0) 40deg 220deg,\n"
"      rgba(0,0,0,.50) 220deg 305deg,\n"
"      rgba(255,255,255,0) 305deg 360deg\n"
"    );\n"
"  box-shadow:\n"
"    inset 0 1px 1px rgba(255,255,255,.05),\n"
"    inset 0 -14px 22px rgba(0,0,0,.78);\n"
"  z-index:-1;\n"
"}\n"
"\n"
"/* embedded ring track + neon */\n"
".drive-ring{\n"
"  position:absolute;\n"
"  inset:6px;\n"
"  border-radius:50%;\n"
"\n"
"  background:\n"
"    /* metal track base */\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 54%, rgba(8,8,9,.95) 58%, rgba(0,0,0,0) 62%),\n"
"    /* neon ring (narrow, embedded) */\n"
"    radial-gradient(circle at 50% 50%,\n"
"      rgba(0,0,0,0) 56%,\n"
"      rgba(255,210,235,.95) 57.2%,\n"
"      rgba(255,120,205,.96) 59.0%,\n"
"      rgba(196,62,126,.98) 61.2%,\n"
"      rgba(70,10,38,.96) 63.2%,\n"
"      rgba(0,0,0,0) 65.0%\n"
"    ),\n"
"    /* highlight arc on ring */\n"
"    conic-gradient(from 300deg,\n"
"      rgba(255,255,255,.42) 0deg 18deg,\n"
"      rgba(255,255,255,.18) 18deg 38deg,\n"
"      rgba(255,255,255,0) 38deg 360deg\n"
"    ),\n"
"    /* inner shadow */\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 62%, rgba(0,0,0,.46) 72%, rgba(0,0,0,.78) 100%);\n"
"\n"
"  border: 2px solid rgba(40,6,22,.92);\n"
"\n"
"  box-shadow:\n"
"    /* embedded glow */\n"
"    0 0 10px rgba(196,62,126,.78),\n"
"    0 0 26px rgba(196,62,126,.30),\n"
"    0 0 54px rgba(196,62,126,.16),\n"
"    inset 0 0 10px rgba(255,210,235,.28),\n"
"    inset 0 0 0 1px rgba(0,0,0,.78);\n"
"\n"
"  transition:\n"
"    opacity 520ms cubic-bezier(.22,.9,.18,1),\n"
"    box-shadow 520ms cubic-bezier(.22,.9,.18,1),\n"
"    filter 520ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* subtle bloom + inner arc */\n"
".drive-ring::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-6px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(196,62,126,.12) 0%, rgba(196,62,126,0) 62%),\n"
"    conic-gradient(from 320deg,\n"
"      rgba(255,255,255,.14) 0deg 34deg,\n"
"      rgba(255,255,255,0) 34deg 360deg\n"
"    );\n"
"  -webkit-mask: radial-gradient(circle, transparent 0 62%, #000 66% 78%, transparent 80% 100%);\n"
"  mask: radial-gradient(circle, transparent 0 62%, #000 66% 78%, transparent 80% 100%);\n"
"  opacity:.55;\n"
"  filter: blur(.35px);\n"
"  pointer-events:none;\n"
"\n"
"  transition: opacity 520ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* inner ring shading */\n"
".drive-ring::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:14px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 32% 24%, rgba(255,255,255,.08), rgba(255,255,255,0) 58%),\n"
"    radial-gradient(circle at 50% 55%, rgba(0,0,0,.66) 56%, rgba(0,0,0,0) 74%);\n"
"  opacity:.70;\n"
"  pointer-events:none;\n"
"\n"
"  transition: opacity 520ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* drive knob cap (radial brushed + specular) */\n"
".drive-knob{\n"
"  --rot:0deg;\n"
"  position:absolute;\n"
"  inset: 18px;\n"
"  border-radius:50%;\n"
"  cursor:pointer;\n"
"  overflow:hidden;\n"
"\n"
"  background:\n"
"    radial-gradient(130% 100% at 32% 18%, rgba(255,255,255,.16) 0%, rgba(255,255,255,0) 38%),\n"
"    radial-gradient(circle at 50% 54%, rgba(255,255,255,.04) 0%, rgba(255,255,255,0) 44%, rgba(0,0,0,.46) 68%, rgba(0,0,0,.86) 100%),\n"
"    repeating-conic-gradient(from 0deg, rgba(255,255,255,.020) 0deg 0.9deg, rgba(0,0,0,0) 0.9deg 3.2deg),\n"
"    radial-gradient(circle at 50% 50%, #1a1a1c 0%, #0f0f11 64%, #040405 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.86);\n"
"  box-shadow:\n"
"    inset 0 2px 2px rgba(255,255,255,.05),\n"
"    inset 0 18px 26px rgba(0,0,0,.56),\n"
"    inset 0 -26px 36px rgba(0,0,0,.90),\n"
"    inset 0 0 0 1px rgba(255,255,255,.02);\n"
"\n"
"  transform: rotate(var(--rot));\n"
"  transition: transform 80ms linear;\n"
"  touch-action: none;\n"
"}\n"
"\n"
"/* subtle texture */\n"
".drive-knob::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:0;\n"
"  background:\n"
"    repeating-linear-gradient(90deg, rgba(255,255,255,.02) 0 1px, rgba(0,0,0,0) 1px 4px);\n"
"  opacity:.10;\n"
"  mix-blend-mode: overlay;\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"/* indicator */\n"
".drive-knob::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  top:12px;\n"
"  left:50%;\n"
"  transform: translateX(-50%);\n"
"  width:3px;\n"
"  height:18px;\n"
"  border-radius:3px;\n"
"  background: linear-gradient(180deg, rgba(255,255,255,.66), rgba(255,255,255,.12));\n"
"  box-shadow:\n"
"    0 1px 2px rgba(0,0,0,.70),\n"
"    inset 0 -1px 1px rgba(0,0,0,.55);\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"#drive-label{\n"
"  position:absolute;\n"
"  top: calc(100% + 16px);\n"
"  left: 50%;\n"
"  transform: translateX(-50%);\n"
"  font-size: clamp(22px, 4vw, 34px);\n"
"  font-weight:800;\n"
"  letter-spacing: 6px;\n"
"  color: #b53a73; /* DIRECT HEX MATCH TO REFERENCE */\n"
"  text-shadow:\n"
"    0 2px 10px rgba(0,0,0,.92),\n"
"    0 0 16px rgba(196,62,126,.14);\n"
"  text-transform: uppercase; /* ALL CAPS LIKE REFERENCE */\n"
"  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif; /* Explicit font declaration */\n"
"}\n"
"\n"
"/* =======================\n"
"   LED area + 2X button (EXACT MATCH)\n"
"   ======================= */\n"
".led-container{\n"
"  position:absolute;\n"
"  left: 18%;\n"
"  top: 83%;\n"
"  transform: translate(-50%, -50%);\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"  align-items:center;\n"
"  gap:8px;\n"
"  z-index:9999;\n"
"}\n"
"\n"
"/* 2X push button (no glow) */\n"
".mini2x{\n"
"  position:absolute;\n"
"  left: 24%;\n"
"  top: 36px;\n"
"  transform: translate(-50%, -50%);\n"
"  width: 20px;\n"
"  height: 20px;\n"
"  border-radius: 50%;\n"
"\n"
"  background:\n"
"    radial-gradient(circle at 35% 30%, rgba(255,255,255,.10) 0%, rgba(255,255,255,0) 34%),\n"
"    radial-gradient(circle at 50% 55%, rgba(0,0,0,0) 0 40%, rgba(0,0,0,.62) 72%, rgba(0,0,0,.92) 100%),\n"
"    radial-gradient(circle at 50% 50%, #1b1b1e 0%, #0d0d10 66%, #040405 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.94);\n"
"  box-shadow:\n"
"    0 8px 14px rgba(0,0,0,.78),\n"
"    inset 0 1px 1px rgba(255,255,255,.08),\n"
"    inset 0 -4px 6px rgba(0,0,0,.90),\n"
"    inset 0 0 0 1px rgba(255,255,255,.03);\n"
"\n"
"  opacity:.96;\n"
"  cursor:pointer;\n"
"  transition: transform .08s ease, box-shadow .12s ease, filter .22s ease;\n"
"  z-index:7;\n"
"}\n"
".mini2x:active{ transform: translate(-50%, -50%) translateY(1px); }\n"
".mini2x.isActive{ filter: brightness(1.06) contrast(1.02); }\n"
"\n"
".mini2x-label{\n"
"  position:absolute;\n"
"  left: 24%;\n"
"  top: 64px;\n"
"  transform: translate(-50%, -50%);\n"
"  color: rgba(210,210,210,.22);\n"
"  font-size: clamp(10px, 1.3vw, 14px);\n"
"  letter-spacing: 2px;\n"
"  text-shadow:\n"
"    0 1px 0 rgba(0,0,0,.92),\n"
"    0 -1px 0 rgba(255,255,255,.06);\n"
"  cursor:pointer;\n"
"  z-index:7;\n"
"  text-transform: uppercase; /* ALL CAPS LIKE REFERENCE */\n"
"  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif; /* Explicit font declaration */\n"
"}\n"
"\n"
"/* LED (SMOOTHER / ANIMATED) */\n"
".led{\n"
"  width: 48px;\n"
"  height: 48px;\n"
"  border-radius:50%;\n"
"  position:relative;\n"
"  cursor:pointer;\n"
"\n"
"  transition:\n"
"    opacity 560ms cubic-bezier(.22,.9,.18,1),\n"
"    box-shadow 560ms cubic-bezier(.22,.9,.18,1),\n"
"    filter 560ms cubic-bezier(.22,.9,.18,1),\n"
"    transform 120ms ease;\n"
"}\n"
"\n"
"/* bezel base */\n"
".led{\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(255,255,255,.06) 0%, rgba(255,255,255,0) 30%, rgba(0,0,0,.62) 60%, rgba(0,0,0,.96) 100%),\n"
"    radial-gradient(circle at 50% 50%, #1a1a1c 0%, #0b0b0d 62%, #040405 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.94);\n"
"  box-shadow:\n"
"    0 14px 22px rgba(0,0,0,.76),\n"
"    inset 0 1px 1px rgba(255,255,255,.08),\n"
"    inset 0 -10px 14px rgba(0,0,0,.90);\n"
"\n"
"  filter: saturate(.35) brightness(.74);\n"
"  opacity:.98;\n"
"  z-index:10000;\n"
"  pointer-events:auto;\n"
"}\n"
"\n"
"/* bezel ring */\n"
".led::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-7px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(0,0,0,0) 56%, rgba(0,0,0,.80) 64%, rgba(0,0,0,1) 80%),\n"
"    conic-gradient(from 320deg,\n"
"      rgba(255,255,255,.14) 0deg 26deg,\n"
"      rgba(255,255,255,0) 26deg 210deg,\n"
"      rgba(0,0,0,.40) 210deg 310deg,\n"
"      rgba(255,255,255,0) 310deg 360deg\n"
"    );\n"
"  -webkit-mask: radial-gradient(circle, transparent 0 56%, #000 62% 100%);\n"
"  mask: radial-gradient(circle, transparent 0 56%, #000 62% 100%);\n"
"  box-shadow:\n"
"    0 12px 18px rgba(0,0,0,.62),\n"
"    inset 0 1px 1px rgba(255,255,255,.06),\n"
"    inset 0 -6px 10px rgba(0,0,0,.84);\n"
"  pointer-events:none;\n"
"  opacity:.95;\n"
"}\n"
"\n"
"/* lens */\n"
".led::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset: 18%;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 30% 28%, rgba(255,255,255,.55) 0%, rgba(255,255,255,.10) 30%, rgba(255,255,255,0) 72%),\n"
"    radial-gradient(circle at 50% 60%, rgba(196,62,126,.18) 0%, rgba(196,62,126,.08) 45%, rgba(0,0,0,0) 78%),\n"
"    radial-gradient(circle at 50% 55%, #101012 0%, #070708 62%, #020203 100%);\n"
"  mix-blend-mode: screen;\n"
"  opacity: 0.22;\n"
"  transform: scale(.94);\n"
"  filter: blur(.15px);\n"
"  transition:\n"
"    opacity 560ms cubic-bezier(.22,.9,.18,1),\n"
"    transform 560ms cubic-bezier(.22,.9,.18,1),\n"
"    filter 560ms cubic-bezier(.22,.9,.18,1);\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"@keyframes ledBreath {\n"
"  0%,100% { box-shadow:\n"
"    0 0 16px rgba(196,62,126,.78),\n"
"    0 0 40px rgba(196,62,126,.30),\n"
"    0 0 72px rgba(196,62,126,.16),\n"
"    0 14px 22px rgba(0,0,0,.62),\n"
"    inset 0 1px 1px rgba(255,255,255,.18); }\n"
"  50% { box-shadow:\n"
"    0 0 20px rgba(196,62,126,.90),\n"
"    0 0 52px rgba(196,62,126,.36),\n"
"    0 0 92px rgba(196,62,126,.18),\n"
"    0 14px 22px rgba(0,0,0,.62),\n"
"    inset 0 1px 1px rgba(255,255,255,.18); }\n"
"}\n"
"\n"
"/* ON state */\n"
".led.isOn{\n"
"  background:\n"
"    radial-gradient(circle at 50% 50%, rgba(255,255,255,.26) 0%, rgba(255,255,255,0) 26%, rgba(0,0,0,.40) 58%, rgba(0,0,0,.92) 100%),\n"
"    radial-gradient(circle at 50% 54%, #2a0a18 0%, #12060b 60%, #040405 100%);\n"
"  filter: saturate(1.15) brightness(1.06);\n"
"  opacity:1;\n"
"  animation: ledBreath 3.2s ease-in-out infinite;\n"
"}\n"
"\n"
"/* stronger lens emission when on */\n"
".led.isOn::after{\n"
"  opacity:.92;\n"
"  transform: scale(1);\n"
"  filter: blur(.05px);\n"
"  background:\n"
"    radial-gradient(circle at 50% 52%, rgba(255,255,255,.95) 0%, rgba(255,190,230,.75) 18%, rgba(255,120,200,.55) 34%, rgba(196,62,126,.24) 60%, rgba(0,0,0,0) 78%),\n"
"    radial-gradient(circle at 30% 26%, rgba(255,255,255,.75) 0%, rgba(255,255,255,0) 62%);\n"
"  mix-blend-mode: screen;\n"
"}\n"
"\n"
".led.isPressed{ transform: translateY(1px); }\n"
"\n"
"/* =======================\n"
"   Output slider (EXACT MATCH)\n"
"   ======================= */\n"
".output-container{\n"
"  position:absolute;\n"
"  left: 50%;\n"
"  top: 83%;\n"
"  transform: translate(-50%, -50%);\n"
"  width: 70%;\n"
"  height: 88px;\n"
"  z-index:6;\n"
"}\n"
"\n"
".slider-track{\n"
"  position:absolute;\n"
"  left: 30%;\n"
"  top: 18px;\n"
"  width: 40%;\n"
"  height:18px;\n"
"  border-radius: 999px;\n"
"\n"
"  background:\n"
"    /* outer rim */\n"
"    linear-gradient(180deg, rgba(255,255,255,.14), rgba(255,255,255,0) 45%),\n"
"    linear-gradient(180deg, #101015, #040405);\n"
"\n"
"  border:1px solid rgba(0,0,0,.96);\n"
"  box-shadow:\n"
"    inset 0 10px 20px rgba(0,0,0,.96),\n"
"    inset 0 -3px 6px rgba(0,0,0,.90),\n"
"    inset 0 1px 0 rgba(255,255,255,.12),\n"
"    inset 0 -1px 0 rgba(0,0,0,.92),\n"
"    0 10px 18px rgba(0,0,0,.58);\n"
"\n"
"  touch-action: none;\n"
"}\n"
"\n"
"/* inner cavity */\n"
".slider-track::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:2px;\n"
"  border-radius:999px;\n"
"  background:\n"
"    radial-gradient(90% 160% at 50% 95%, rgba(0,0,0,.92), rgba(0,0,0,0) 70%),\n"
"    linear-gradient(180deg, rgba(255,255,255,.05), rgba(255,255,255,0) 60%),\n"
"    linear-gradient(180deg, #060607, #020203);\n"
"  box-shadow:\n"
"    inset 0 2px 6px rgba(0,0,0,.92),\n"
"    inset 0 1px 0 rgba(255,255,255,.04);\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"/* rim line */\n"
".slider-track::after{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-2px;\n"
"  border-radius:999px;\n"
"  background: linear-gradient(180deg, rgba(255,255,255,.06), rgba(0,0,0,.26));\n"
"  opacity:.55;\n"
"  pointer-events:none;\n"
"}\n"
"\n"
"/* handle (more cylindrical) */\n"
".slider-thumb{\n"
"  position:absolute;\n"
"  top:50%;\n"
"  left:50%;\n"
"  transform: translate(-50%, -50%);\n"
"  width: 16px;\n"
"  height: 34px;\n"
"  border-radius: 8px;\n"
"\n"
"  background:\n"
"    /* cylindrical highlight */\n"
"    linear-gradient(90deg,\n"
"      rgba(255,255,255,.28) 0%,\n"
"      rgba(255,255,255,.08) 22%,\n"
"      rgba(0,0,0,0) 52%,\n"
"      rgba(0,0,0,.22) 78%,\n"
"      rgba(0,0,0,.40) 100%),\n"
"    /* metal body */\n"
"    linear-gradient(180deg, #5a5a60, #303036, #141418);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.92);\n"
"\n"
"  box-shadow:\n"
"    0 12px 18px rgba(0,0,0,.86),\n"
"    0 2px 6px rgba(0,0,0,.66),\n"
"    inset 0 1px 0 rgba(255,255,255,.18),\n"
"    inset 0 -3px 4px rgba(0,0,0,.78),\n"
"    0 0 0 1px rgba(255,255,255,.06);\n"
"\n"
"  cursor:pointer;\n"
"  touch-action: none;\n"
"}\n"
"\n"
"/* tiny grip */\n"
".slider-thumb::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  top:50%; left:50%;\n"
"  transform: translate(-50%, -50%);\n"
"  width:10px; height:2px;\n"
"  background: rgba(255,255,255,.24);\n"
"  box-shadow:\n"
"    0 1px 0 rgba(0,0,0,.80),\n"
"    0 -1px 0 rgba(255,255,255,.10);\n"
"  border-radius:2px;\n"
"}\n"
"\n"
".output-label{\n"
"  position:absolute;\n"
"  right: 2%;\n"
"  top: 18px;\n"
"  transform: translateY(26px);\n"
"  white-space: nowrap;\n"
"  color: var(--text-engrave-weak);\n"
"  font-size: clamp(9px, 1.2vw, 12px);\n"
"  letter-spacing: 2px;\n"
"  text-shadow:\n"
"    0 1px 0 rgba(0,0,0,.92),\n"
"    0 -1px 0 rgba(255,255,255,.06);\n"
"  text-transform: uppercase; /* ALL CAPS LIKE REFERENCE */\n"
"  font-family: 'Barlow', 'Segoe UI', Arial, sans-serif; /* Explicit font declaration */\n"
"}\n"
"\n"
"/* small hole */\n"
".tiny-hole{\n"
"  position:absolute;\n"
"  right: 12%;\n"
"  top: 30px;\n"
"  width: 10px;\n"
"  height: 10px;\n"
"  border-radius:50%;\n"
"  background:\n"
"    radial-gradient(circle at 50% 45%, rgba(0,0,0,.35) 0%, rgba(0,0,0,.86) 60%, #020202 100%),\n"
"    radial-gradient(circle at 40% 30%, rgba(255,255,255,.10) 0%, rgba(255,255,255,0) 55%);\n"
"  box-shadow:\n"
"    inset 0 1px 1px rgba(255,255,255,.04),\n"
"    inset 0 -2px 3px rgba(0,0,0,.78);\n"
"  opacity:.85;\n"
"}\n"
"\n"
"/* =======================\n"
"   Bottom neon (EXACT MATCH)\n"
"   ======================= */\n"
".bottom-line{\n"
"  position:absolute;\n"
"  left: 7%;\n"
"  right: 7%;\n"
"  bottom: 4%;\n"
"  height: 4px;\n"
"  border-radius: 4px;\n"
"\n"
"  background:\n"
"    /* core line */\n"
"    linear-gradient(90deg, transparent 0%, rgba(196,62,126,.22) 18%, rgba(196,62,126,.92) 50%, rgba(196,62,126,.22) 82%, transparent 100%);\n"
"\n"
"  box-shadow:\n"
"    0 0 10px rgba(196,62,126,.46),\n"
"    0 0 28px rgba(196,62,126,.20),\n"
"    0 12px 22px rgba(0,0,0,.70);\n"
"\n"
"  opacity:.92;\n"
"  transition: opacity 520ms cubic-bezier(.22,.9,.18,1), filter 520ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* =======================\n"
"   Interaction safety\n"
"   ======================= */\n"
".panel::before,\n"
".panel::after,\n"
".grain{ pointer-events:none; }\n"
"\n"
"#satclip-group, #mix-group { right: auto !important; }\n"
"#pre-group, #trim-group, #satclip-group, #mix-group { transform: translate(-50%, -50%) !important; }\n"
".drive-container, .led-container, .output-container { transform: translate(-50%, -50%) !important; }\n"
"\n"
".small-knob,\n"
".drive-knob,\n"
".slider-track,\n"
".slider-thumb,\n"
".led{\n"
"  touch-action: none;\n"
"}\n"
"\n"
"/* =======================\n"
"   Power states (match your existing JS class toggles)\n"
"   ======================= */\n"
".powerOff .drive-ring,\n"
".powerOff .drive-ring::before,\n"
".powerOff .drive-ring::after{\n"
"  opacity:0;\n"
"  box-shadow:none;\n"
"}\n"
".powerOff .drive-container::before{ opacity:0; }\n"
"\n"
".powerOff .bottom-line{\n"
"  opacity:.16;\n"
"  filter:saturate(.60) brightness(.72);\n"
"}\n"
"\n"
".powerOff .panel{ filter: brightness(.78) saturate(.86); }\n"
".powerOff .header{ filter: brightness(.78) saturate(.72); }\n"
"\n"
".powerOn .drive-ring,\n"
".powerOn .drive-ring::before,\n"
".powerOn .drive-ring::after,\n"
".powerOn .drive-container::before{\n"
"  opacity:1;\n"
"}\n"
"\n"
"/* ensure clickable */\n"
".led, .mini2x, .mini2x-label{ pointer-events:auto; }\n"
"\n"
"\n"
"/* =======================\n"
"   Credit \"i\" button + Modal\n"
"   ======================= */\n"
"\n"
"/* small info button (metal, engraved) */\n"
".info-btn{\n"
"  position:absolute;\n"
"  right: 6.4%;\n"
"  bottom: 6.0%;\n"
"  width: 28px;\n"
"  height: 28px;\n"
"  border-radius: 999px;\n"
"  display:grid;\n"
"  place-items:center;\n"
"\n"
"  font-family: 'Barlow','Segoe UI',Arial,sans-serif;\n"
"  font-weight: 800;\n"
"  font-size: 16px;\n"
"  line-height: 1;\n"
"  color: rgba(235,235,235,.44);\n"
"  letter-spacing: .2px;\n"
"\n"
"  background:\n"
"    radial-gradient(circle at 30% 22%, rgba(255,255,255,.14) 0%, rgba(255,255,255,0) 38%),\n"
"    radial-gradient(circle at 50% 55%, rgba(0,0,0,0) 0 42%, rgba(0,0,0,.66) 72%, rgba(0,0,0,.92) 100%),\n"
"    radial-gradient(circle at 50% 50%, #1b1b1e 0%, #0d0d10 66%, #040405 100%);\n"
"\n"
"  border: 1px solid rgba(0,0,0,.94);\n"
"  box-shadow:\n"
"    0 10px 16px rgba(0,0,0,.78),\n"
"    inset 0 1px 1px rgba(255,255,255,.08),\n"
"    inset 0 -4px 6px rgba(0,0,0,.90),\n"
"    inset 0 0 0 1px rgba(255,255,255,.03);\n"
"\n"
"  cursor:pointer;\n"
"  z-index: 50;\n"
"  transition:\n"
"    transform 120ms ease,\n"
"    box-shadow 260ms cubic-bezier(.22,.9,.18,1),\n"
"    color 260ms cubic-bezier(.22,.9,.18,1),\n"
"    filter 260ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
".info-btn:hover{\n"
"  color: rgba(255,255,255,.60);\n"
"  filter: brightness(1.05);\n"
"}\n"
".info-btn:active{\n"
"  transform: translateY(1px);\n"
"}\n"
"\n"
"/* backdrop */\n"
".modal-backdrop{\n"
"  position:absolute;\n"
"  inset:0;\n"
"  display:grid;\n"
"  place-items:center;\n"
"\n"
"  background: rgba(0,0,0,.72); /* (opsional) lebih gelap biar LED ga tembus */\n"
"  backdrop-filter: blur(7px) saturate(1.05);\n"
"  -webkit-backdrop-filter: blur(7px) saturate(1.05);\n"
"\n"
"  opacity:0;\n"
"  pointer-events:none;\n"
"\n"
"  z-index: 20000;   /* <<< NAIKKAN INI */\n"
"  transition: opacity 360ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
".modal{\n"
"  z-index: 20001;   /* <<< biar modal di atas backdrop */\n"
"}\n"
"\n"
"/* open state */\n"
".modal-backdrop.isOpen{\n"
"  opacity:1;\n"
"  pointer-events:auto;\n"
"}\n"
"\n"
"/* modal panel */\n"
".modal{\n"
"  width: min(520px, 86%);\n"
"  border-radius: 14px;\n"
"  position:relative;\n"
"\n"
"  background:\n"
"    linear-gradient(180deg, rgba(255,255,255,.06), rgba(0,0,0,.10)),\n"
"    repeating-linear-gradient(\n"
"      90deg,\n"
"      rgba(255,255,255,.018) 0px,\n"
"      rgba(255,255,255,.006) 1px,\n"
"      rgba(0,0,0,.018) 3px,\n"
"      rgba(0,0,0,0) 6px\n"
"    ),\n"
"    linear-gradient(180deg, #15161a 0%, #0a0b0f 50%, #07070a 100%);\n"
"\n"
"  border: 1px solid rgba(255,255,255,.05);\n"
"  box-shadow:\n"
"    0 28px 70px rgba(0,0,0,.86),\n"
"    0 12px 26px rgba(0,0,0,.62),\n"
"    inset 0 1px 0 rgba(255,255,255,.06),\n"
"    inset 0 -18px 30px rgba(0,0,0,.62),\n"
"    inset 0 0 0 1px rgba(0,0,0,.70);\n"
"\n"
"  transform: translateY(10px) scale(.985);\n"
"  opacity: 0;\n"
"  transition:\n"
"    transform 420ms cubic-bezier(.22,.9,.18,1),\n"
"    opacity 420ms cubic-bezier(.22,.9,.18,1);\n"
"}\n"
"\n"
"/* pop-in when open */\n"
".modal-backdrop.isOpen .modal{\n"
"  transform: translateY(0px) scale(1);\n"
"  opacity: 1;\n"
"}\n"
"\n"
"/* top subtle magenta edge */\n"
".modal::before{\n"
"  content:'';\n"
"  position:absolute;\n"
"  inset:-1px;\n"
"  border-radius: 14px;\n"
"  background:\n"
"    radial-gradient(110% 90% at 50% 0%, rgba(196,62,126,.22) 0%, rgba(196,62,126,0) 62%),\n"
"    radial-gradient(120% 120% at 50% 50%, rgba(255,255,255,.04) 0%, rgba(255,255,255,0) 58%);\n"
"  pointer-events:none;\n"
"  opacity:.85;\n"
"  mask: linear-gradient(#000,#000);\n"
"}\n"
"\n"
"/* header row */\n"
".modal-head{\n"
"  display:flex;\n"
"  align-items:center;\n"
"  justify-content:space-between;\n"
"  padding: 14px 16px 10px 16px;\n"
"  border-bottom: 1px solid rgba(255,255,255,.06);\n"
"}\n"
"\n"
".modal-title{\n"
"  font-family:'Barlow','Segoe UI',Arial,sans-serif;\n"
"  font-weight: 900;\n"
"  letter-spacing: 3px;\n"
"  font-size: 14px;\n"
"  color: rgba(181,58,115,.92);\n"
"  text-transform: uppercase;\n"
"  text-shadow: 0 2px 10px rgba(0,0,0,.92);\n"
"}\n"
"\n"
".modal-close{\n"
"  width: 30px;\n"
"  height: 30px;\n"
"  border-radius: 999px;\n"
"  border: 1px solid rgba(0,0,0,.88);\n"
"  background:\n"
"    radial-gradient(circle at 30% 22%, rgba(255,255,255,.12) 0%, rgba(255,255,255,0) 40%),\n"
"    radial-gradient(circle at 50% 55%, rgba(0,0,0,0) 0 40%, rgba(0,0,0,.66) 74%, rgba(0,0,0,.92) 100%),\n"
"    radial-gradient(circle at 50% 50%, #1b1b1e 0%, #0d0d10 66%, #040405 100%);\n"
"  color: rgba(255,255,255,.52);\n"
"  cursor:pointer;\n"
"\n"
"  box-shadow:\n"
"    0 10px 16px rgba(0,0,0,.74),\n"
"    inset 0 1px 1px rgba(255,255,255,.08),\n"
"    inset 0 -4px 6px rgba(0,0,0,.90);\n"
"\n"
"  transition: transform 120ms ease, filter 220ms ease, color 220ms ease;\n"
"}\n"
".modal-close:hover{ color: rgba(255,255,255,.68); filter: brightness(1.05); }\n"
".modal-close:active{ transform: translateY(1px); }\n"
"\n"
".modal-body{\n"
"  padding: 14px 16px 16px 16px;\n"
"}\n"
"\n"
".credit-lines{\n"
"  display:flex;\n"
"  flex-direction:column;\n"
"  gap: 10px;\n"
"}\n"
"\n"
".credit-row{\n"
"  display:flex;\n"
"  justify-content:space-between;\n"
"  align-items:baseline;\n"
"  gap: 12px;\n"
"}\n"
"\n"
".credit-k{\n"
"  color: rgba(210,210,210,.22);\n"
"  font-size: 11px;\n"
"  letter-spacing: 2px;\n"
"  text-transform: uppercase;\n"
"  text-shadow: 0 1px 0 rgba(0,0,0,.92), 0 -1px 0 rgba(255,255,255,.05);\n"
"}\n"
"\n"
".credit-v{\n"
"  color: rgba(225,225,225,.34);\n"
"  font-size: 12px;\n"
"  letter-spacing: 1px;\n"
"  text-shadow: 0 1px 0 rgba(0,0,0,.92), 0 -1px 0 rgba(255,255,255,.05);\n"
"}\n"
"\n"
".credit-divider{\n"
"  height: 1px;\n"
"  background: linear-gradient(90deg, transparent, rgba(196,62,126,.28), transparent);\n"
"  opacity: .9;\n"
"  margin: 6px 0;\n"
"}\n"
"\n"
".credit-note{\n"
"  color: rgba(210,210,210,.18);\n"
"  font-size: 11px;\n"
"  letter-spacing: 1px;\n"
"  line-height: 1.35;\n"
"}\n";

const char* style_css = (const char*) temp_binary_data_2;


const char* getNamedResource (const char* resourceNameUTF8, int& numBytes);
const char* getNamedResource (const char* resourceNameUTF8, int& numBytes)
{
    unsigned int hash = 0;

    if (resourceNameUTF8 != nullptr)
        while (*resourceNameUTF8 != 0)
            hash = 31 * hash + (unsigned int) *resourceNameUTF8++;

    switch (hash)
    {
        case 0xabe4b827:  numBytes = 8818; return app_js;
        case 0x2c834af8:  numBytes = 3823; return index_html;
        case 0x6b9f8e75:  numBytes = 31692; return style_css;
        default: break;
    }

    numBytes = 0;
    return nullptr;
}

const char* namedResourceList[] =
{
    "app_js",
    "index_html",
    "style_css"
};

const char* originalFilenames[] =
{
    "app.js",
    "index.html",
    "style.css"
};

const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8);
const char* getNamedResourceOriginalFilename (const char* resourceNameUTF8)
{
    for (unsigned int i = 0; i < (sizeof (namedResourceList) / sizeof (namedResourceList[0])); ++i)
        if (strcmp (namedResourceList[i], resourceNameUTF8) == 0)
            return originalFilenames[i];

    return nullptr;
}

}
